id: P005525
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG15936
  title: དབུ་མ་རྩ་བའི་ཚིག་ལེའུར་བྱས་པ་ཤེས་རབ་ཅེས་བྱ་བའི་རྣམ་བཤད་རིགས་པའི་རྒྱ་མཚོ།
  author: ''
  volumes:
    29c75cbef14b4dac88be59b83df06e30:
      image_group_id: I1KG15945
      title: ''
      volume_number: 1
      total_pages: 460
      base_file: v001.txt
    125a9b6a705748c9ac9c73ca5074575b:
      image_group_id: I1KG15946
      title: ''
      volume_number: 2
      total_pages: 427
      base_file: v002.txt
