id: IEFF4C62A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T14:55:08+00:00'
last_modified: '2022-06-08T03:42:19.432078+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15936
  title: དབུ་མ་རྩ་བའི་ཚིག་ལེའུར་བྱས་པ་ཤེས་རབ་ཅེས་བྱ་བའི་རྣམ་བཤད་རིགས་པའི་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    04D1:
      image_group_id: I1KG15945
      title: ''
      total_pages: 460
      order: 1
      base_file: 04D1.txt
    8BCA:
      image_group_id: I1KG15946
      title: ''
      total_pages: 427
      order: 2
      base_file: 8BCA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
